/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.huesped;
import Entidades.reserva;
import accesoAdatos.huespedData;
import accesoAdatos.reservaData;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author perey
 */
public class ListarReserva extends javax.swing.JInternalFrame {

    reservaData listar = new reservaData();
    DefaultTableModel formatoTabla = new DefaultTableModel();
    ArrayList<reserva> res= new ArrayList<> ();
    /**
     * Creates new form ListarReserva
     */
    public ListarReserva() {
        initComponents();
//        listar.listarreserva();
        inicializarTabla();
        cargarTabla();
        jTingreso.setText("Ingresar IdHuesped");
        jTingreso.setBackground(Color.GREEN);
        jTingreso.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistares = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTdato = new javax.swing.JTextField();
        jTingreso = new javax.swing.JToggleButton();
        jBbuscar = new javax.swing.JButton();
        jTdia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTmes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTanio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBreset = new javax.swing.JButton();

        jTlistares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTlistares);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Reservas");

        jTdato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdatoActionPerformed(evt);
            }
        });

        jTingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTingresoActionPerformed(evt);
            }
        });

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jTdia.setEnabled(false);

        jLabel2.setText("/");

        jTmes.setEnabled(false);

        jLabel3.setText("/");

        jTanio.setEnabled(false);
        jTanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTanioActionPerformed(evt);
            }
        });

        jLabel4.setText("dd");

        jLabel5.setText("mm");

        jLabel6.setText("aaaa");

        jBreset.setText("Reiniciar Tabla");
        jBreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTdato, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTdia, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTmes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jBbuscar)
                                        .addGap(51, 51, 51)
                                        .addComponent(jBreset)
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTanio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBbuscar)
                                .addComponent(jBreset)))
                        .addGap(8, 8, 8)))
                .addComponent(jTdato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTingresoActionPerformed
        if (jTingreso.isSelected()) {
            jTingreso.setText("Ingresar Fecha");
            jTingreso.setBackground(Color.RED);
            jTingreso.setForeground(Color.WHITE);
            jTdato.enable(false);
            jTdia.enable(true);
            jTmes.enable(true);
            jTanio.enable(true);

        } else {
            jTingreso.setText("Ingresar IdHuesped");
            jTingreso.setBackground(Color.GREEN);
            jTingreso.setForeground(Color.BLACK);
            jTdato.enable(true);
            jTdia.enable(false);
            jTmes.enable(false);
            jTanio.enable(false);
        }
    }//GEN-LAST:event_jTingresoActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        limpiarT();
        String aux =jTdato.getText();
         String auxd =jTdia.getText();
          String auxm =jTmes.getText();
           String auxa =jTanio.getText();
          
    if(jTingreso.getText()=="Ingresar Fecha"){
        reserva r=new reserva();
                if(auxd.isEmpty()|| auxm.isEmpty()|| auxa.isEmpty()&&!aux.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha valida por favor ");
        }else {
        int dia=Integer.parseInt(jTdia.getText());
        int mes=Integer.parseInt(jTmes.getText());
        int anio=Integer.parseInt(jTanio.getText());
        LocalDate fecha= LocalDate.of(anio, mes, dia);
        res=(ArrayList)listar.buscarresevaxfecha(fecha);
                }
         for (reserva item : res) {
//            System.out.println(""+item);
            formatoTabla.addRow(new Object[]{item.getIdReserva(), item.getIdHuesped().getApellidoynom(), item.getNrohabitacion().getNumero(), item.getFechaEntrada(), item.getFechaSalida(), item.getImporteTotal()});
        }
        
        
        
        jTdia.setText("");
        jTmes.setText("");
        jTanio.setText("");
        
    } else if (jTingreso.getText()=="Ingresar IdHuesped"){
        huespedData h=new huespedData ();
        huesped buscado = new huesped();
         if(aux.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo con un Id por favor ");
         } else { 
        int id=Integer.parseInt(jTdato.getText());
       buscado= h.buscarporId(id);
//        h.setIdHuesped(Integer.parseInt(jTdato.getText()));
         }
               res= (ArrayList)listar.buscarreservaxhuesped(buscado);
        for (reserva item : res) {
            System.out.println(""+item);
            formatoTabla.addRow(new Object[]{item.getIdReserva(),  item.getIdHuesped().getApellidoynom(), item.getNrohabitacion().getNumero(), item.getFechaEntrada(), item.getFechaSalida(), item.getImporteTotal()});
        }
        jTdato.setText("");
    }
   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jTanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTanioActionPerformed

    private void jTdatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdatoActionPerformed

    private void jBresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetActionPerformed
        limpiarT();
        cargarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBresetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTanio;
    private javax.swing.JTextField jTdato;
    private javax.swing.JTextField jTdia;
    private javax.swing.JToggleButton jTingreso;
    private javax.swing.JTable jTlistares;
    private javax.swing.JTextField jTmes;
    // End of variables declaration//GEN-END:variables

    public void inicializarTabla() {

        formatoTabla.addColumn("IdReserva");
        formatoTabla.addColumn("Huesped");
        formatoTabla.addColumn("N° de Habitacion");
        formatoTabla.addColumn("Fecha de Entrada");
        formatoTabla.addColumn("Fecha de Salida");
        formatoTabla.addColumn("Importe Total");
//        formatoTabla.addColumn("");
        jTlistares.setModel(formatoTabla);
    }

    public void cargarTabla() {
        ArrayList<reserva> lista = new ArrayList<>();
        lista = (ArrayList) listar.listarreserva();
        for (reserva item : lista) {
            formatoTabla.addRow(new Object[]{item.getIdReserva(), item.getIdHuesped().getApellidoynom(), item.getNrohabitacion().getNumero(), item.getFechaEntrada(), item.getFechaSalida(), item.getImporteTotal()});
        }

    }

    private void limpiarT() {
        int ind = formatoTabla.getRowCount() - 1;
        for (int x = ind; x >= 0; x--) {
            formatoTabla.removeRow(x);
        }
    }

}
